version: '2.4'
services:
  mysql:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: todo
    ports:
    - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-P", "3306", "-uroot", "-ptoor"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
